server:
  port: 9095
  servlet.context-path: /extjs
  undertow.max-http-post-size: 0
  error:
    include-message: always
spring:
  application.name: extjs
  threads.virtual.enabled: true
  main.allow-bean-definition-overriding: true
  jackson.default-property-inclusion: non_absent
  freemarker.check-template-location: false
  servlet.multipart.max-file-size: 5MB
  servlet.multipart.max-request-size: 5MB
  servlet.multipart.resolve-lazily: true
  thymeleaf:
    cache: false
    check-template-location: true
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    template-resolver-order: 1
